export const ERROR_CODES = {
  VALIDATION: {
    INVALID_INPUT: 'VALIDATION.INVALID_INPUT',
    MISSING_FIELD: 'VALIDATION.MISSING_FIELD',
    INVALID_FORMAT: 'VALIDATION.INVALID_FORMAT',
  },

  AUTH: {
    INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'AUTH.TOKEN_EXPIRED',
    TOKEN_INVALID: 'AUTH.TOKEN_INVALID',
    TOKEN_REVOKED: 'AUTH.TOKEN_REVOKED',
    TOKEN_REUSE_DETECTED: 'AUTH.TOKEN_REUSE_DETECTED',
    EMAIL_TAKEN: 'AUTH.EMAIL_TAKEN',
    UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
    FORBIDDEN: 'AUTH.FORBIDDEN',
    INSUFFICIENT_TIER: 'AUTH.INSUFFICIENT_TIER',
    API_KEY_INVALID: 'AUTH.API_KEY_INVALID',
    API_KEY_EXPIRED: 'AUTH.API_KEY_EXPIRED',
    API_KEY_REVOKED: 'AUTH.API_KEY_REVOKED',
  },

  VALUATION: {
    INSUFFICIENT_DATA: 'VALUATION.INSUFFICIENT_DATA',
    NO_COMPARABLES: 'VALUATION.NO_COMPARABLES',
    ML_SIDECAR_DOWN: 'VALUATION.ML_SIDECAR_DOWN',
    ML_SIDECAR_ERROR: 'VALUATION.ML_SIDECAR_ERROR',
    MODEL_NOT_LOADED: 'VALUATION.MODEL_NOT_LOADED',
  },

  NOT_FOUND: {
    USER: 'NOT_FOUND.USER',
    VALUATION: 'NOT_FOUND.VALUATION',
    REPORT: 'NOT_FOUND.REPORT',
    API_KEY_ID: 'NOT_FOUND.API_KEY_ID',
    MODEL_VERSION: 'NOT_FOUND.MODEL_VERSION',
    SCRAPING_TARGET: 'NOT_FOUND.SCRAPING_TARGET',
    ROUTE: 'NOT_FOUND.ROUTE',
  },

  RATE_LIMIT: {
    EXCEEDED: 'RATE_LIMIT.EXCEEDED',
  },

  INTERNAL: {
    UNKNOWN: 'INTERNAL.UNKNOWN',
    DATABASE: 'INTERNAL.DATABASE',
    EXTERNAL_SERVICE: 'INTERNAL.EXTERNAL_SERVICE',
  },

  PIPELINE: {
    SCRAPE_FAILED: 'PIPELINE.SCRAPE_FAILED',
    DISCOVER_FAILED: 'PIPELINE.DISCOVER_FAILED',
    ENRICHMENT_FAILED: 'PIPELINE.ENRICHMENT_FAILED',
    GEOCODING_FAILED: 'PIPELINE.GEOCODING_FAILED',
  },

  PAYMENT: {
    INVOICE_FAILED: 'PAYMENT.INVOICE_FAILED',
    WEBHOOK_INVALID: 'PAYMENT.WEBHOOK_INVALID',
    WEBHOOK_SIGNATURE: 'PAYMENT.WEBHOOK_SIGNATURE',
  },

  REPORT: {
    GENERATION_FAILED: 'REPORT.GENERATION_FAILED',
  },

  HEATMAP: {
    NO_DATA: 'HEATMAP.NO_DATA',
    GENERATION_FAILED: 'HEATMAP.GENERATION_FAILED',
  },

  AREA: {
    CACHE_EXPIRED: 'AREA.CACHE_EXPIRED',
    FETCH_FAILED: 'AREA.FETCH_FAILED',
    SUMMARIZATION_FAILED: 'AREA.SUMMARIZATION_FAILED',
  },

  CRAWL: {
    SEED_NOT_FOUND: 'CRAWL.SEED_NOT_FOUND',
    JOB_NOT_FOUND: 'CRAWL.JOB_NOT_FOUND',
    CRAWL_FAILED: 'CRAWL.CRAWL_FAILED',
    EXTRACTION_FAILED: 'CRAWL.EXTRACTION_FAILED',
  },
} as const;

export type ErrorCode =
  (typeof ERROR_CODES)[keyof typeof ERROR_CODES][keyof (typeof ERROR_CODES)[keyof typeof ERROR_CODES]];
