packages:
  - packages/*
  - apps/gavai/*
  - libs/*

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  less: true
  nx: true
  sharp: true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
  '@scarf/scarf': true
  '@prisma/engines': true
  prisma: true
  bcrypt: true
  msgpackr-extract: true
  puppeteer: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - less
  - msgpackr-extract
  - nx
  - prisma
  - sharp
  - unrs-resolver
