packages:
  - 'packages/*'
  - 'apps/gabai/*'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  less: true
  nx: true
  sharp: true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
