import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const prisma = new PrismaClient({
  adapter: new PrismaPg(process.env.DATABASE_URL!),
});

interface GovSeedData {
  barangay: string;
  city: string;
  zonalValuePhp: number | null;
  landClassification: string;
  phivolcsRisk: number;
  floodRisk: number;
  barangayMultiplier: number;
  priceTrend6m: number | null;
}

// ============================================================
// CEBU CITY (80 barangays)
// North District: 46, South District: 34
// Premium center: 40K-85K, mid: 15K-35K, outskirts: 5K-15K
// ============================================================

const CEBU_CITY_DATA: GovSeedData[] = [
  // ---- North District - Premium / CBD ----
  {
    barangay: 'Capitol Site',
    city: 'Cebu City',
    zonalValuePhp: 58000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.3,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Cebu Business Park',
    city: 'Cebu City',
    zonalValuePhp: 85000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.5,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Kamputhaw',
    city: 'Cebu City',
    zonalValuePhp: 55000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.15,
    barangayMultiplier: 1.28,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Lahug',
    city: 'Cebu City',
    zonalValuePhp: 45000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Mabolo',
    city: 'Cebu City',
    zonalValuePhp: 50000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Banilad',
    city: 'Cebu City',
    zonalValuePhp: 52000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Apas',
    city: 'Cebu City',
    zonalValuePhp: 42000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.15,
    barangayMultiplier: 1.12,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Kasambagan',
    city: 'Cebu City',
    zonalValuePhp: 48000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 1.18,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Ermita',
    city: 'Cebu City',
    zonalValuePhp: 35000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.3,
    floodRisk: 0.25,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Santo Niño',
    city: 'Cebu City',
    zonalValuePhp: 60000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 1.35,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Pari-an',
    city: 'Cebu City',
    zonalValuePhp: 42000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'San Roque',
    city: 'Cebu City',
    zonalValuePhp: 38000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Zapatera',
    city: 'Cebu City',
    zonalValuePhp: 36000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 1.02,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Kalubihan',
    city: 'Cebu City',
    zonalValuePhp: 40000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 1.08,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Kamagayan',
    city: 'Cebu City',
    zonalValuePhp: 38000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Cogon Ramos',
    city: 'Cebu City',
    zonalValuePhp: 32000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Day-as',
    city: 'Cebu City',
    zonalValuePhp: 34000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.25,
    barangayMultiplier: 0.98,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Pahina Central',
    city: 'Cebu City',
    zonalValuePhp: 35000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Tinago',
    city: 'Cebu City',
    zonalValuePhp: 32000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.35,
    barangayMultiplier: 0.92,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Tejero',
    city: 'Cebu City',
    zonalValuePhp: 28000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.35,
    barangayMultiplier: 0.88,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Carreta',
    city: 'Cebu City',
    zonalValuePhp: 27000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.35,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Hipodromo',
    city: 'Cebu City',
    zonalValuePhp: 26000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.3,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Lorega San Miguel',
    city: 'Cebu City',
    zonalValuePhp: 24000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.35,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Luz',
    city: 'Cebu City',
    zonalValuePhp: 30000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Santa Cruz',
    city: 'Cebu City',
    zonalValuePhp: 33000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'San Antonio',
    city: 'Cebu City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.3,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'San Jose',
    city: 'Cebu City',
    zonalValuePhp: 21000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.35,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Mabini',
    city: 'Cebu City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.35,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'T. Padilla',
    city: 'Cebu City',
    zonalValuePhp: 19000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },

  // ---- North District - Upland / Suburban ----
  {
    barangay: 'Talamban',
    city: 'Cebu City',
    zonalValuePhp: 25000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Bacayan',
    city: 'Cebu City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Pit-os',
    city: 'Cebu City',
    zonalValuePhp: 15000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Pulangbato',
    city: 'Cebu City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Busay',
    city: 'Cebu City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Lusaran',
    city: 'Cebu City',
    zonalValuePhp: 8000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.55,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Binaliw',
    city: 'Cebu City',
    zonalValuePhp: 9000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.6,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Guba',
    city: 'Cebu City',
    zonalValuePhp: 5000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.45,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Cambinocot',
    city: 'Cebu City',
    zonalValuePhp: 6000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.48,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Budla-an',
    city: 'Cebu City',
    zonalValuePhp: 7000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.5,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Sirao',
    city: 'Cebu City',
    zonalValuePhp: 10000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.58,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Malubog',
    city: 'Cebu City',
    zonalValuePhp: 6000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.45,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Taptap',
    city: 'Cebu City',
    zonalValuePhp: 5500,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.42,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Adlawon',
    city: 'Cebu City',
    zonalValuePhp: 7000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.5,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Agsungot',
    city: 'Cebu City',
    zonalValuePhp: 6500,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.15,
    floodRisk: 0.25,
    barangayMultiplier: 0.48,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Paril',
    city: 'Cebu City',
    zonalValuePhp: 6000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.45,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Sambag I',
    city: 'Cebu City',
    zonalValuePhp: 23000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Sambag II',
    city: 'Cebu City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },

  // ---- South District - Central / Mid ----
  {
    barangay: 'Guadalupe',
    city: 'Cebu City',
    zonalValuePhp: 30000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.25,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Labangon',
    city: 'Cebu City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Tisa',
    city: 'Cebu City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.35,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Punta Princesa',
    city: 'Cebu City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.35,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Mambaling',
    city: 'Cebu City',
    zonalValuePhp: 20000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.4,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Basak San Nicolas',
    city: 'Cebu City',
    zonalValuePhp: 19000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.4,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Pardo',
    city: 'Cebu City',
    zonalValuePhp: 15000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Bulacao',
    city: 'Cebu City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Inayawan',
    city: 'Cebu City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.35,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Quiot',
    city: 'Cebu City',
    zonalValuePhp: 12000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.4,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Basak Pardo',
    city: 'Cebu City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.35,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Kinasang-an Pardo',
    city: 'Cebu City',
    zonalValuePhp: 13000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Poblacion Pardo',
    city: 'Cebu City',
    zonalValuePhp: 18000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Cogon Pardo',
    city: 'Cebu City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Pahina San Nicolas',
    city: 'Cebu City',
    zonalValuePhp: 17000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.35,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'San Nicolas Proper',
    city: 'Cebu City',
    zonalValuePhp: 22000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.35,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Duljo Fatima',
    city: 'Cebu City',
    zonalValuePhp: 17000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.4,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Pasil',
    city: 'Cebu City',
    zonalValuePhp: 15000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.45,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Sawang Calero',
    city: 'Cebu City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.4,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Suba',
    city: 'Cebu City',
    zonalValuePhp: 17000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.4,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Calamba',
    city: 'Cebu City',
    zonalValuePhp: 28000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.3,
    barangayMultiplier: 0.88,
    priceTrend6m: 0.02,
  },

  // ---- South District - Upland / Fringe ----
  {
    barangay: 'Kalunasan',
    city: 'Cebu City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.2,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Buhisan',
    city: 'Cebu City',
    zonalValuePhp: 12000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.25,
    barangayMultiplier: 0.68,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Sapangdaku',
    city: 'Cebu City',
    zonalValuePhp: 11000,
    landClassification: 'Residential',
    phivolcsRisk: 0.35,
    floodRisk: 0.25,
    barangayMultiplier: 0.65,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Babag',
    city: 'Cebu City',
    zonalValuePhp: 8000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.55,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Bonbon',
    city: 'Cebu City',
    zonalValuePhp: 9000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.58,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Pamutan',
    city: 'Cebu City',
    zonalValuePhp: 5000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.42,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Sudlon I',
    city: 'Cebu City',
    zonalValuePhp: 5500,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.45,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Sudlon II',
    city: 'Cebu City',
    zonalValuePhp: 5000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.42,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Sinsin',
    city: 'Cebu City',
    zonalValuePhp: 4500,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.4,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Tabunan',
    city: 'Cebu City',
    zonalValuePhp: 4000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.38,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Tagbao',
    city: 'Cebu City',
    zonalValuePhp: 6500,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.48,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Toong',
    city: 'Cebu City',
    zonalValuePhp: 6000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.45,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Buot',
    city: 'Cebu City',
    zonalValuePhp: 7000,
    landClassification: 'Agricultural',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.5,
    priceTrend6m: 0.0,
  },
];

// ============================================================
// MANDAUE CITY (27 barangays) — Industrial/Mixed 15K-45K
// ============================================================

const MANDAUE_DATA: GovSeedData[] = [
  {
    barangay: 'Centro',
    city: 'Mandaue City',
    zonalValuePhp: 40000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Tipolo',
    city: 'Mandaue City',
    zonalValuePhp: 35000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Subangdaku',
    city: 'Mandaue City',
    zonalValuePhp: 32000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Guizo',
    city: 'Mandaue City',
    zonalValuePhp: 38000,
    landClassification: 'Industrial',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Mantuyong',
    city: 'Mandaue City',
    zonalValuePhp: 28000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Looc',
    city: 'Mandaue City',
    zonalValuePhp: 30000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.35,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Maguikay',
    city: 'Mandaue City',
    zonalValuePhp: 30000,
    landClassification: 'Industrial',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Opao',
    city: 'Mandaue City',
    zonalValuePhp: 32000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Ibabao-Estancia',
    city: 'Mandaue City',
    zonalValuePhp: 28000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Paknaan',
    city: 'Mandaue City',
    zonalValuePhp: 25000,
    landClassification: 'Industrial',
    phivolcsRisk: 0.2,
    floodRisk: 0.35,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Tabok',
    city: 'Mandaue City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.35,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Cambaro',
    city: 'Mandaue City',
    zonalValuePhp: 24000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Pagsabungan',
    city: 'Mandaue City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Umapad',
    city: 'Mandaue City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.35,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Cabancalan',
    city: 'Mandaue City',
    zonalValuePhp: 24000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Banilad',
    city: 'Mandaue City',
    zonalValuePhp: 45000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Bakilid',
    city: 'Mandaue City',
    zonalValuePhp: 25000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Canduman',
    city: 'Mandaue City',
    zonalValuePhp: 25000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Casuntingan',
    city: 'Mandaue City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Casili',
    city: 'Mandaue City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Labogon',
    city: 'Mandaue City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Jagobiao',
    city: 'Mandaue City',
    zonalValuePhp: 15000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Basak',
    city: 'Mandaue City',
    zonalValuePhp: 20000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.35,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Alang-alang',
    city: 'Mandaue City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.35,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Cubacub',
    city: 'Mandaue City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Tawason',
    city: 'Mandaue City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.15,
    floodRisk: 0.3,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Tingub',
    city: 'Mandaue City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
];

// ============================================================
// LAPU-LAPU CITY (30 barangays) — Tourism/Residential 12K-40K
// ============================================================

const LAPULAPU_DATA: GovSeedData[] = [
  {
    barangay: 'Pusok',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 38000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 1.12,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Mactan',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 40000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Ibo',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 35000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 1.08,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Pajo',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 32000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Poblacion',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 30000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Maribago',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 35000,
    landClassification: 'Tourism',
    phivolcsRisk: 0.35,
    floodRisk: 0.15,
    barangayMultiplier: 1.08,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Marigondon',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 25000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 0.88,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Bankal',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 24000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Gun-ob',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.15,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Looc',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 26000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Basak',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Babag',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Agus',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 24000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Buaya',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 22000,
    landClassification: 'Mixed',
    phivolcsRisk: 0.25,
    floodRisk: 0.15,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Pajac',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Punta Engano',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 38000,
    landClassification: 'Tourism',
    phivolcsRisk: 0.35,
    floodRisk: 0.15,
    barangayMultiplier: 1.12,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Sabang',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 22000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Santa Rosa',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'San Vicente',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Canjulao',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.2,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Calawisan',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 15000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Subabasbas',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.68,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Baring',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 13000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.65,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Caw-oy',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 12000,
    landClassification: 'Residential',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.65,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Tingo',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 12000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.62,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Tungasan',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.68,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Caubian',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 10000,
    landClassification: 'Residential',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.58,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Cawhagan',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 10000,
    landClassification: 'Residential',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.55,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Pangan-an',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 11000,
    landClassification: 'Residential',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.58,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Talima',
    city: 'Lapu-Lapu City',
    zonalValuePhp: 10000,
    landClassification: 'Residential',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.55,
    priceTrend6m: 0.0,
  },
];

// ============================================================
// TALISAY CITY (22 barangays) — Suburban/Residential 8K-25K
// ============================================================

const TALISAY_DATA: GovSeedData[] = [
  {
    barangay: 'Poblacion',
    city: 'Talisay City',
    zonalValuePhp: 22000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Tabunok',
    city: 'Talisay City',
    zonalValuePhp: 25000,
    landClassification: 'Commercial',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Bulacao',
    city: 'Talisay City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Lawaan I',
    city: 'Talisay City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.82,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Lawaan II',
    city: 'Talisay City',
    zonalValuePhp: 19000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Lawaan III',
    city: 'Talisay City',
    zonalValuePhp: 18000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Pooc',
    city: 'Talisay City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.35,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Tangke',
    city: 'Talisay City',
    zonalValuePhp: 20000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Cansojong',
    city: 'Talisay City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'San Isidro',
    city: 'Talisay City',
    zonalValuePhp: 17000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.78,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'San Roque',
    city: 'Talisay City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Biasong',
    city: 'Talisay City',
    zonalValuePhp: 13000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.68,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Dumlog',
    city: 'Talisay City',
    zonalValuePhp: 16000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.25,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.01,
  },
  {
    barangay: 'Jaclupan',
    city: 'Talisay City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Lagtang',
    city: 'Talisay City',
    zonalValuePhp: 13000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.68,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Linao',
    city: 'Talisay City',
    zonalValuePhp: 12000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.65,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Mohon',
    city: 'Talisay City',
    zonalValuePhp: 14000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.72,
    priceTrend6m: 0.005,
  },
  {
    barangay: 'Cadulawan',
    city: 'Talisay City',
    zonalValuePhp: 10000,
    landClassification: 'Residential',
    phivolcsRisk: 0.2,
    floodRisk: 0.3,
    barangayMultiplier: 0.6,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Camp IV',
    city: 'Talisay City',
    zonalValuePhp: 8000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.55,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Maghaway',
    city: 'Talisay City',
    zonalValuePhp: 9000,
    landClassification: 'Residential',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.58,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Tapul',
    city: 'Talisay City',
    zonalValuePhp: 10000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.3,
    barangayMultiplier: 0.6,
    priceTrend6m: 0.0,
  },
  {
    barangay: 'Tina-an',
    city: 'Talisay City',
    zonalValuePhp: 11000,
    landClassification: 'Residential',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.62,
    priceTrend6m: 0.0,
  },
];

// ============================================================
// MAIN
// ============================================================

async function main(): Promise<void> {
  const allData: GovSeedData[] = [
    ...CEBU_CITY_DATA,
    ...MANDAUE_DATA,
    ...LAPULAPU_DATA,
    ...TALISAY_DATA,
  ];

  let count = 0;
  for (const data of allData) {
    await prisma.governmentReference.upsert({
      where: {
        barangay_city: {
          barangay: data.barangay,
          city: data.city,
        },
      },
      update: {
        zonalValuePhp: data.zonalValuePhp,
        landClassification: data.landClassification,
        phivolcsRisk: data.phivolcsRisk,
        floodRisk: data.floodRisk,
        barangayMultiplier: data.barangayMultiplier,
        priceTrend6m: data.priceTrend6m,
      },
      create: {
        barangay: data.barangay,
        city: data.city,
        zonalValuePhp: data.zonalValuePhp,
        landClassification: data.landClassification,
        phivolcsRisk: data.phivolcsRisk,
        floodRisk: data.floodRisk,
        barangayMultiplier: data.barangayMultiplier,
        priceTrend6m: data.priceTrend6m,
      },
    });
    count++;
    console.log(
      `[${count}/${allData.length}] Seeded: ${data.barangay}, ${data.city}`,
    );
  }

  console.log(`\nDone! Seeded ${count} barangays across Metro Cebu.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
