import { PrismaClient } from '@prisma/client';

interface GovernmentSeedEntry {
  barangay: string;
  zonalValuePhp: number;
  landClassification: string;
  phivolcsRisk: number;
  floodRisk: number;
  barangayMultiplier: number;
  priceTrend6m: number;
}

const MANILA_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Barangay 1',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangay 2',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangay 669',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Barangay 670',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Binondo',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Ermita',
    zonalValuePhp: 40000,
    landClassification: 'CR',
    phivolcsRisk: 0.25,
    floodRisk: 0.1,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Intramuros',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Malate',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.25,
    floodRisk: 0.1,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Paco',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Pandacan',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'San Andres',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'San Miguel',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Nicolas',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santa Ana',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santa Cruz',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Santa Mesa',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Sampaloc',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Tondo',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.35,
    floodRisk: 0.25,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Quiapo',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.3,
    floodRisk: 0.15,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Port Area',
    zonalValuePhp: 30000,
    landClassification: 'I',
    phivolcsRisk: 0.3,
    floodRisk: 0.2,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
];

const MANDALUYONG_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Addition Hills',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Bagong Silang',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangka Drive',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangka Ibaba',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangka Ilaya',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangka Itaas',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Buayang Bato',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Burol',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Daang Bakal',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Hagdang Bato Itaas',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Hagdang Bato Libis',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Harapin Ang Bukas',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Highway Hills',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Hulo',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Mabini-J. Rizal',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Malamig',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Mauway',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Namayan',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'New Zaniga',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Old Zaniga',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Pag-Asa',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Plainview',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Pleasant Hills',
    zonalValuePhp: 40000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Poblacion',
    zonalValuePhp: 34000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'San Jose',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Vergara',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Wack-Wack Greenhills',
    zonalValuePhp: 55000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.3,
    priceTrend6m: 0.09,
  },
];

const PASIG_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Bagong Ilog',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Bagong Katipunan',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Bambang',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Buting',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Caniogan',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Capitol Commons',
    zonalValuePhp: 50000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'Kapitolyo',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Malinao',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Manggahan',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Maybunga',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Oranbo',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Ortigas Center',
    zonalValuePhp: 55000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.3,
    priceTrend6m: 0.09,
  },
  {
    barangay: 'Palatiw',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Pinagbuhatan',
    zonalValuePhp: 20000,
    landClassification: 'CR',
    phivolcsRisk: 0.25,
    floodRisk: 0.25,
    barangayMultiplier: 0.75,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Pineda',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Rosario',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Antonio',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'San Joaquin',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'San Jose',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'San Nicolas',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santa Cruz',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Santa Lucia',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santa Rosa',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santo Tomas',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santolan',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Sumilang',
    zonalValuePhp: 23000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.2,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Ugong',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Ugong Norte',
    zonalValuePhp: 48000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
];

const MAKATI_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Bangkal',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Bel-Air',
    zonalValuePhp: 100000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.5,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'Carmona',
    zonalValuePhp: 50000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Cembo',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Comembo',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Dasmariñas',
    zonalValuePhp: 110000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.6,
    priceTrend6m: 0.12,
  },
  {
    barangay: 'East Rembo',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Forbes Park',
    zonalValuePhp: 130000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.8,
    priceTrend6m: 0.12,
  },
  {
    barangay: 'Guadalupe Nuevo',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Guadalupe Viejo',
    zonalValuePhp: 40000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'La Paz',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Magallanes',
    zonalValuePhp: 75000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.4,
    priceTrend6m: 0.09,
  },
  {
    barangay: 'Olympia',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Palanan',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Pembo',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Pinagkaisahan',
    zonalValuePhp: 55000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Pio del Pilar',
    zonalValuePhp: 48000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Poblacion',
    zonalValuePhp: 55000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Rembo',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Salcedo',
    zonalValuePhp: 110000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.6,
    priceTrend6m: 0.12,
  },
  {
    barangay: 'San Antonio',
    zonalValuePhp: 100000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.5,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'San Isidro',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'San Lorenzo',
    zonalValuePhp: 120000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.7,
    priceTrend6m: 0.12,
  },
  {
    barangay: 'Santa Cruz',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Singkamas',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Tejeros',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Urdaneta',
    zonalValuePhp: 120000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.7,
    priceTrend6m: 0.12,
  },
  {
    barangay: 'Valenzuela',
    zonalValuePhp: 50000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'West Rembo',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.06,
  },
];

const QC_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Bagbag',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Bagong Pag-asa',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Balingasa',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Batasan Hills',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Botocan',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Central',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Commonwealth',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Cubao',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Culiat',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Diliman',
    zonalValuePhp: 40000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Doña Imelda',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Fairview',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Holy Spirit',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Kamuning',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Katipunan',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Krus na Ligas',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Loyola Heights',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'New Era',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Novaliches proper',
    zonalValuePhp: 20000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Pansol',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Pasong Putik',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Pasong Tamo',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Payatas',
    zonalValuePhp: 15000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.7,
    priceTrend6m: 0.02,
  },
  {
    barangay: 'Pinagkaisahan',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Project 4',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Project 6',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Roxas',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Sacred Heart',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Saint Peter',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'San Martin de Porres',
    zonalValuePhp: 22000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Santa Cruz',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Santo Domingo',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Sauyo',
    zonalValuePhp: 20000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'Sikatuna Village',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Socorro',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'South Triangle',
    zonalValuePhp: 40000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Tandang Sora',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Ugong Norte',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'University of the Philippines Campus',
    zonalValuePhp: 32000,
    landClassification: 'I',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'U.P. Village',
    zonalValuePhp: 52000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.3,
    priceTrend6m: 0.09,
  },
  {
    barangay: 'Vasra',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Veterans Village',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'West Triangle',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'White Plains',
    zonalValuePhp: 60000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.35,
    priceTrend6m: 0.09,
  },
];

const TAGUIG_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Bagumbayan',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Bambang',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Bonifacio Global City',
    zonalValuePhp: 110000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.6,
    priceTrend6m: 0.12,
  },
  {
    barangay: 'Calzada',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Central Bicutan',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Fort Bonifacio',
    zonalValuePhp: 100000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.5,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'Hagonoy',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Ibayo-Tipas',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Katuparan',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Ligid-Tipas',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Lower Bicutan',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Maharlika Village',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Napindan',
    zonalValuePhp: 24000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.8,
    priceTrend6m: 0.03,
  },
  {
    barangay: 'New Lower Bicutan',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'New Upper Bicutan',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Palingon',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Pembo',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Pinagsama',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Poblacion',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Miguel',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Santa Ana',
    zonalValuePhp: 26000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Signal Village',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Tuktukan',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Upper Bicutan',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Ususan',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Wawa',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.2,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Western Bicutan',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
];

const SAN_JUAN_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Addition Hills',
    zonalValuePhp: 45000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Balong-Bato',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Batis',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Corazon de Jesus',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Ermitaño',
    zonalValuePhp: 40000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Greenhills',
    zonalValuePhp: 70000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.4,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'Isabelita',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Kabayanan',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Little Baguio',
    zonalValuePhp: 52000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.09,
  },
  {
    barangay: 'Maytunas',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Onse',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Pasadeña',
    zonalValuePhp: 42000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.15,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'Pedro Cruz',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Progreso',
    zonalValuePhp: 34000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Rivera',
    zonalValuePhp: 36000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Salapan',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Perfecto',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Santa Lucia',
    zonalValuePhp: 38000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.1,
    priceTrend6m: 0.07,
  },
  {
    barangay: 'St. Joseph',
    zonalValuePhp: 36000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.05,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'Tibagan',
    zonalValuePhp: 34000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.06,
  },
  {
    barangay: 'West Crame',
    zonalValuePhp: 48000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.2,
    priceTrend6m: 0.08,
  },
];

const PASAY_BARANGAYS: GovernmentSeedEntry[] = [
  {
    barangay: 'Barangay 1',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangay 13',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Barangay 76',
    zonalValuePhp: 50000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Barangay 77',
    zonalValuePhp: 50000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.25,
    priceTrend6m: 0.08,
  },
  {
    barangay: 'Bay City',
    zonalValuePhp: 80000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.5,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'Don Carlos Village',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Marcelo Village',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Maricaban',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'MOA Complex',
    zonalValuePhp: 75000,
    landClassification: 'CR',
    phivolcsRisk: 0.1,
    floodRisk: 0.02,
    barangayMultiplier: 1.45,
    priceTrend6m: 0.1,
  },
  {
    barangay: 'Malibay',
    zonalValuePhp: 25000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.85,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'Newport City',
    zonalValuePhp: 65000,
    landClassification: 'CR',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.35,
    priceTrend6m: 0.09,
  },
  {
    barangay: 'Pasay Rotonda',
    zonalValuePhp: 35000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Isidro',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Jose',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'San Rafael',
    zonalValuePhp: 28000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.15,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.04,
  },
  {
    barangay: 'San Roque',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Santa Clara',
    zonalValuePhp: 32000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Santo Niño',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.9,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Tramo',
    zonalValuePhp: 30000,
    landClassification: 'CR',
    phivolcsRisk: 0.2,
    floodRisk: 0.1,
    barangayMultiplier: 0.95,
    priceTrend6m: 0.05,
  },
  {
    barangay: 'Villamor Air Base',
    zonalValuePhp: 35000,
    landClassification: 'I',
    phivolcsRisk: 0.15,
    floodRisk: 0.05,
    barangayMultiplier: 1.0,
    priceTrend6m: 0.05,
  },
];

const CITY_MAP: Record<
  string,
  { city: string; barangays: GovernmentSeedEntry[] }
> = {
  Manila: { city: 'Manila', barangays: MANILA_BARANGAYS },
  Mandaluyong: { city: 'Mandaluyong', barangays: MANDALUYONG_BARANGAYS },
  Pasig: { city: 'Pasig', barangays: PASIG_BARANGAYS },
  Makati: { city: 'Makati', barangays: MAKATI_BARANGAYS },
  'Quezon City': { city: 'Quezon City', barangays: QC_BARANGAYS },
  Taguig: { city: 'Taguig', barangays: TAGUIG_BARANGAYS },
  'San Juan': { city: 'San Juan', barangays: SAN_JUAN_BARANGAYS },
  Pasay: { city: 'Pasay', barangays: PASAY_BARANGAYS },
};

async function main(): Promise<void> {
  const prisma = new PrismaClient();

  const cityName = process.argv[2];
  const citiesToSeed = cityName
    ? [CITY_MAP[cityName]].filter(Boolean)
    : Object.values(CITY_MAP);

  if (cityName && citiesToSeed.length === 0) {
    console.error(
      `City "${cityName}" not found. Available: ${Object.keys(CITY_MAP).join(', ')}`,
    );
    process.exit(1);
  }

  for (const { city, barangays } of citiesToSeed) {
    console.log(`Seeding ${city} (${barangays.length} barangays)...`);
    let count = 0;

    for (const entry of barangays) {
      await prisma.governmentReference.upsert({
        where: {
          barangay_city: {
            barangay: entry.barangay,
            city,
          },
        },
        update: {
          zonalValuePhp: entry.zonalValuePhp,
          landClassification: entry.landClassification,
          phivolcsRisk: entry.phivolcsRisk,
          floodRisk: entry.floodRisk,
          barangayMultiplier: entry.barangayMultiplier,
          priceTrend6m: entry.priceTrend6m,
        },
        create: {
          barangay: entry.barangay,
          city,
          zonalValuePhp: entry.zonalValuePhp,
          landClassification: entry.landClassification,
          phivolcsRisk: entry.phivolcsRisk,
          floodRisk: entry.floodRisk,
          barangayMultiplier: entry.barangayMultiplier,
          priceTrend6m: entry.priceTrend6m,
        },
      });
      count++;
    }

    console.log(`  Inserted/updated ${count} records for ${city}`);
  }

  console.log('Done.');
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
